"use client";

import { useState } from "react";
import { Sidebar } from "@/components/dashboard/sidebar";
import { MobileNav } from "@/components/dashboard/mobile-nav";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Bot, CheckCircle2, KeyRound, LogOut, Pencil, ShieldCheck, UserRound, UsersRound, X } from "lucide-react";

const partners = [
  { name: "Aditya Sharma", email: "aditya@example.com", initials: "AS", you: true },
  { name: "Vishal Kumar Singh", email: "vishal@example.com", initials: "VK" },
  { name: "Ujjwal Kumar Singh", email: "ujjwal@example.com", initials: "UK" },
];

export default function SettingsPage() {
  const [name, setName] = useState("Aditya Sharma");
  const [editOpen, setEditOpen] = useState(false);
  const [passwordOpen, setPasswordOpen] = useState(false);
  const [telegramOpen, setTelegramOpen] = useState(false);
  const [connected, setConnected] = useState(true);
  return <div className="min-h-screen bg-[#fff8f1] selection:bg-[#fee3b5] selection:text-[#1d1e1c] md:flex"><Sidebar /><MobileNav /><main className="w-full flex-1 px-4 py-6 sm:px-6 sm:py-8 md:p-8 lg:p-10"><div className="mx-auto max-w-5xl space-y-7">
    <header className="border-b border-[#e3d6c5]/70 pb-5"><p className="mb-1 text-xs font-semibold uppercase tracking-[0.15em] text-[#fa5d00]">Partner finance</p><h1 className="text-3xl font-bold tracking-tight text-[#1d1e1c] sm:text-4xl">Settings</h1><p className="mt-1 text-sm text-[#615f5c] sm:text-base">Manage your account and workspace preferences.</p></header>
    <SettingsSection title="Profile Information" description="Your account details in this private workspace." icon={UserRound}><Card className="border-[#e3d6c5] p-5 sm:p-6"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div className="flex items-center gap-4"><Avatar initials="AS" large /><div><h3 className="text-lg font-bold text-[#1d1e1c]">{name}</h3><p className="mt-0.5 text-sm text-[#615f5c]">aditya@example.com</p><p className="mt-2 text-xs font-medium text-[#8e8b87]">Email address cannot be changed here.</p></div></div><Button variant="secondary" onClick={() => setEditOpen(true)} className="w-full sm:w-auto"><Pencil className="h-4 w-4 text-[#fa5d00]" /> Edit Profile</Button></div></Card></SettingsSection>
    <SettingsSection title="Security" description="Keep your account secure." icon={ShieldCheck}><Card className="border-[#e3d6c5] p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h3 className="font-bold text-[#1d1e1c]">Password</h3><p className="mt-1 font-mono tracking-[0.2em] text-[#615f5c]">••••••••••</p></div><Button variant="secondary" onClick={() => setPasswordOpen(true)} className="w-full sm:w-auto"><KeyRound className="h-4 w-4 text-[#fa5d00]" /> Change Password</Button></div></Card></SettingsSection>
    <SettingsSection title="Telegram Connection" description="Connect with the finance bot to record updates from Telegram." icon={Bot}><Card className={`border p-5 sm:p-6 ${connected ? "border-[#fee3b5]" : "border-[#e3d6c5]"}`}><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div className="flex items-start gap-3"><div className={`mt-0.5 flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${connected ? "bg-emerald-50 text-emerald-600" : "bg-[#fff8f1] text-[#8e8b87]"}`}><Bot className="h-5 w-5" /></div><div><div className="flex items-center gap-2"><h3 className="font-bold text-[#1d1e1c]">{connected ? "Connected" : "Not Connected"}</h3><span className={`h-2.5 w-2.5 rounded-full ${connected ? "bg-emerald-500" : "bg-[#c0bbb6]"}`} /></div><p className="mt-1 max-w-md text-sm leading-relaxed text-[#615f5c]">{connected ? "Your Telegram ID is linked to your account." : "Connect your Telegram account to add expenses and settlements directly from Telegram."}</p></div></div><Button variant={connected ? "secondary" : "primary"} onClick={() => setTelegramOpen(true)} className="w-full sm:w-auto">{connected ? "Manage Connection" : "Connect Telegram"}</Button></div></Card></SettingsSection>
    <SettingsSection title="Partner Workspace" description="This is a private workspace with only authorized partners." icon={UsersRound}><Card className="border-[#e3d6c5] p-0"><div className="border-b border-[#e3d6c5] bg-[#fff8f1]/60 px-5 py-3.5 text-xs font-semibold uppercase tracking-wider text-[#615f5c]">3 authorized partners</div><div className="divide-y divide-[#e3d6c5]/70">{partners.map((partner) => <div key={partner.email} className="flex items-center justify-between gap-3 px-5 py-4 sm:px-6"><div className="flex min-w-0 items-center gap-3"><Avatar initials={partner.initials} /><div className="min-w-0"><div className="flex items-center gap-2"><p className="truncate text-sm font-semibold text-[#1d1e1c]">{partner.name}</p>{partner.you && <span className="rounded-full bg-[#fa5d00]/10 px-2 py-0.5 text-[10px] font-bold uppercase text-[#fa5d00]">You</span>}</div><p className="truncate text-xs text-[#8e8b87]">{partner.email}</p></div></div><span className="inline-flex shrink-0 items-center gap-1.5 text-xs font-semibold text-emerald-700"><span className="h-2 w-2 rounded-full bg-emerald-500" /><span className="hidden sm:inline">Authorized</span></span></div>)}</div></Card></SettingsSection>
    <section className="border-t border-[#e3d6c5] pt-7"><div className="mb-4"><h2 className="text-xl font-bold text-[#1d1e1c]">Danger Zone</h2><p className="mt-0.5 text-sm text-[#615f5c]">Actions that affect your current sessions.</p></div><Card className="border-[#e3d6c5] bg-white p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h3 className="font-bold text-[#1d1e1c]">Log out of all devices</h3><p className="mt-1 text-sm text-[#615f5c]">End all active sessions, including this one.</p></div><Button variant="outline" className="w-full border-red-300 text-red-600 hover:bg-red-50 sm:w-auto"><LogOut className="h-4 w-4" /> Log Out of All Devices</Button></div></Card></section>
  </div></main>{editOpen && <EditProfile initialName={name} onClose={() => setEditOpen(false)} onSave={(value) => { setName(value); setEditOpen(false); }} />}{passwordOpen && <ChangePassword onClose={() => setPasswordOpen(false)} />}{telegramOpen && <TelegramModal connected={connected} onClose={() => setTelegramOpen(false)} onToggle={() => { setConnected((state) => !state); setTelegramOpen(false); }} />}</div>;
}

function SettingsSection({ title, description, icon: Icon, children }: { title: string; description: string; icon: typeof UserRound; children: React.ReactNode }) { return <section><div className="mb-4 flex items-start gap-2.5"><div className="mt-0.5 text-[#fa5d00]"><Icon className="h-5 w-5" /></div><div><h2 className="text-xl font-bold text-[#1d1e1c]">{title}</h2><p className="mt-0.5 text-sm text-[#615f5c]">{description}</p></div></div>{children}</section>; }
function Avatar({ initials, large = false }: { initials: string; large?: boolean }) { return <div className={`${large ? "h-14 w-14 text-base" : "h-10 w-10 text-xs"} flex shrink-0 items-center justify-center rounded-full bg-[#fa5d00] font-bold text-white shadow-sm`}>{initials}</div>; }
function Modal({ title, description, children, onClose }: { title: string; description: string; children: React.ReactNode; onClose: () => void }) { return <div className="fixed inset-0 z-[60] flex items-end bg-[#1d1e1c]/45 backdrop-blur-sm sm:items-center sm:justify-center sm:p-4" role="dialog" aria-modal="true" aria-label={title}><div className="w-full max-w-lg rounded-t-[24px] border border-[#e3d6c5] bg-white p-5 shadow-2xl sm:rounded-[24px] sm:p-7"><div className="flex items-start justify-between gap-4 border-b border-[#e3d6c5] pb-4"><div><h2 className="text-xl font-bold text-[#1d1e1c]">{title}</h2><p className="mt-1 text-sm text-[#615f5c]">{description}</p></div><button aria-label="Close dialog" onClick={onClose} className="rounded-full p-1.5 text-[#8e8b87] hover:bg-[#fff8f1]"><X className="h-5 w-5" /></button></div>{children}</div></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-xs font-semibold uppercase tracking-wider text-[#1d1e1c]"><span className="mb-1.5 block">{label}</span>{children}</label>; }
function EditProfile({ initialName, onClose, onSave }: { initialName: string; onClose: () => void; onSave: (value: string) => void }) { const [name, setName] = useState(initialName); return <Modal title="Edit profile" description="Update the name and avatar shown in the workspace." onClose={onClose}><form onSubmit={(event) => { event.preventDefault(); if (name.trim()) onSave(name.trim()); }} className="space-y-5 pt-5"><div className="flex items-center gap-4"><Avatar initials={name.split(" ").map((word) => word[0]).join("").slice(0, 2) || "AS"} large /><button type="button" className="text-sm font-semibold text-[#fa5d00] hover:underline">Change avatar</button></div><Field label="Full name"><Input value={name} onChange={(event) => setName(event.target.value)} required /></Field><div><p className="text-xs font-semibold uppercase tracking-wider text-[#1d1e1c]">Email address</p><p className="mt-2 text-sm text-[#615f5c]">aditya@example.com</p></div><div className="flex justify-end gap-3 border-t border-[#e3d6c5] pt-4"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit">Save Changes</Button></div></form></Modal>; }
function ChangePassword({ onClose }: { onClose: () => void }) { const [updated, setUpdated] = useState(false); return <Modal title="Change password" description="Use a strong password you do not use elsewhere." onClose={onClose}>{updated ? <div className="py-10 text-center"><CheckCircle2 className="mx-auto h-11 w-11 text-emerald-600" /><h3 className="mt-3 font-bold text-[#1d1e1c]">Password updated</h3><Button size="sm" onClick={onClose} className="mt-5">Done</Button></div> : <form onSubmit={(event) => { event.preventDefault(); setUpdated(true); }} className="space-y-4 pt-5"><Field label="Current password"><Input type="password" required /></Field><Field label="New password"><Input type="password" minLength={8} required /></Field><Field label="Confirm new password"><Input type="password" minLength={8} required /></Field><div className="flex justify-end gap-3 border-t border-[#e3d6c5] pt-4"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit">Update Password</Button></div></form>}</Modal>; }
function TelegramModal({ connected, onClose, onToggle }: { connected: boolean; onClose: () => void; onToggle: () => void }) { return <Modal title={connected ? "Manage Telegram connection" : "Connect Telegram"} description={connected ? "Your account is currently linked to the finance bot." : "Link Telegram to record shared-finance updates quickly."} onClose={onClose}><div className="space-y-5 py-5"><div className="flex items-center gap-3 rounded-[16px] border border-[#e3d6c5] bg-[#fff8f1] p-4"><Bot className="h-5 w-5 text-[#fa5d00]" /><div><p className="font-semibold text-[#1d1e1c]">Finance Tracker Bot</p><p className="text-xs text-[#615f5c]">{connected ? "Connected as @aditya" : "No Telegram account connected"}</p></div></div><div className="flex justify-end gap-3 border-t border-[#e3d6c5] pt-4"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button variant={connected ? "outline" : "primary"} onClick={onToggle} className={connected ? "border-red-300 text-red-600 hover:bg-red-50" : ""}>{connected ? "Disconnect Telegram" : "Connect Telegram"}</Button></div></div></Modal>; }
